# Generated by Django 3.1.7 on 2021-06-03 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='completion_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DES', 'Design'), ('QTE', 'Quote'), ('DPST', 'Deposit'), ('SCRNSHR', 'Screenshare'), ('DIGPRF', 'Digital Proof'), ('SMPLPROD', 'Sample Production'), ('WHLSLPROD', 'Wholesale Production'), ('SHIP', 'Shipping')], max_length=30)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=300, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='completion_date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Stageupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stageupdates', to='project.stage')),
            ],
        ),
    ]
