# Generated by Django 3.1.7 on 2021-06-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('DESIGN', 'Design'), ('QUOTE', 'Quote'), ('DEPOSIT', 'Deposit'), ('SCREENSHARE', 'Screenshare'), ('DIGITAL_PROOF', 'Digital Proof'), ('SAMPLE_PRODUCTION', 'Sample Production'), ('WHOLESALE_PRODUCTION', 'Wholesale Production'), ('SHIPPING', 'Shipping')], max_length=30),
        ),
    ]
